# Channels:
#
# name - (Required) name of the public or private channel.
# topic - (Optional) topic for the channel.
# purpose - (Optional) purpose of the channel.
# permanent_members - (Optional) user IDs to add to the channel.
# is_private - (Optional) create a private channel instead of a public one.
# is_archived - (Optional) indicates a conversation is archived. Frozen in time.
# action_on_destroy - (Optional, Default archive) indicates whether the conversation should be archived or left behind on destroy. Valid values are archive | none. Note that when set to none the conversation will be left as it is and as a result any subsequent runs of terraform apply with the same name will fail.
# data_source - (Optional) data source to use for the list of user IDs to add to the channel. Valid values are maintainers_user_ids | ambassadors_user_ids | tsc_user_ids right now.

# NOTE:-
# 1. The channel name should be unique.
# 2. The user IDs should be valid and should be present in the workspace.
# 3. Either permanent_members or data_source should be provided to add users to the channel.
# 4. The default value for change in permanent_members is kick for private channels and nothing for public channels.
# 5. The default value for adopt_current_channels is true.

- name: random-test
  topic: Non-work banter and water cooler conversation
  purpose: A place for non-work-related flimflam, faffing, hodge-podge or jibber-jabber you'd prefer to keep out of more focused work-related channels.
  permanent_members:
    - U06QFSWLDA6
    - U06R6V51YSC
    - U06Q3J4SR5M
    - U06QWQKA51P
  is_private: false
  is_archived: false
  action_on_destroy: archive

- name: maintainers
  topic: Private channel for maintainers of the test environment
  purpose: A private channel for the maintainers of the test environment to discuss and share information.
  data_source: maintainers_user_ids
  is_private: true
  is_archived: false
  action_on_destroy: archive

- name: ambassadors
  topic: Private channel for ambassadors of the test environment
  purpose: A private channel for the ambassadors of the test environment to discuss and share information.
  data_source: ambassadors_user_ids
  is_private: true
  is_archived: false
  action_on_destroy: archive